# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 08:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lb', '0002_auto_20160623_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='lb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lb.LearningBoard'),
        ),
    ]
