# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-27 09:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lb', '0003_auto_20160625_0539'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
