# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 18:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lb', '0003_auto_20160624_0843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='activity',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='type',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
