# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lb', '0004_auto_20160625_0211'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningboard',
            name='level',
            field=models.PositiveSmallIntegerField(choices=[(0, b'Beginner'), (1, b'Intermediate'), (2, b'Advanced')], default=0),
        ),
    ]
