# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 06:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lb', '0005_learningboard_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[(b'PB', b'published'), (b'UP', b'unpublished')], default=b'UP', max_length=127),
        ),
    ]
